    
    
    'Erode': ['Sathyamangalam', 'Gobichettipalayam', 'erode', 'Modakkurichi', 'Anthiyur', 'Bhavani', 'Bhavanisagar', 'Kangeyam', 'Perundurai', 'Vellakoil'],    
    'Coimbatore': ['Avinashi', 'coimbatore', 'Dharapuram', 'Kinathukkadavu', 'Mettupalayam', 'Palladam', 'Perur', 'Pollachi', 'Pongalur', 'Singanallur','Thondamuthur',
                   'Tirupur', 'Udumalipet', 'Valparai'],
    'Ariyalur': ['ariyalur', 'Andimadam', 'Udayarpalayam', 'Sendurai'],
    'Chennai': ['Aadambakkam', 'Adyar', 'Alwarpet', 'Ambattur', 'Anna Nagar Arcot', 'Annanagar', 'Annasalai', 'Ashok Nagar', 'Avadi', 'Ayanavaram', 'Besant Nagar', 'Broadway', 'Chepauk', 'Chetput', 'Chitlepakkam',
                'Choolaimedu', 'Chrompet', 'Dr.radhakrushnan Nagar', 'Egmore', 'Ennore', 'Guindy', 'Harbour', 'Jaffarkhanpet', 'Jawahar Nagar', 'Kamaraj Nagar', 'Kilpauk', 'Kodambakkam', 'Kolathur', 'Korattur', 'Kottupuram',
                'Madhavaram', 'Madipakkam', 'Mambalam', 'Manali', 'Manapakkam', 'Minambakkam', 'Mylapore', 'Nandambakkam', 'Nandanam', 'Nanganallur', 'Nungambakkam', 'Padi', 'Pallavaram', 'Pammal', 'Park town', 'Perambur',
                'Porur', 'Purasawalkam', 'Ramapuram', 'Royapuram', 'Saidapet', 'Tambaram', 'Theagaraya Nagar', 'Thiruvanmiyur', 'Thiruvottiyur', 'Thousand Lights', 'Tirsulam', 'Tondiarpet', 'Triplicane', 'Vadapalani',
                'Vandalur', 'Velacherry', 'Villiwakkam', 'Virugambakkam', 'Washermanpet'],
    'Cuddalore': ['Bhuvanagiri', 'Chidambaram', 'cuddalore', 'Kattumannarkoil', 'Kurinjipadi', 'Mangalore', 'Nellikuppam', 'Neyveli', 'Panruti', 'Vridhachalam'],
    'Dharmapuri': ['dharmapuri', 'Harur', 'Morrapur', 'Palacode', 'Pennagaram'],
    'Dindigul': ['Athoor', 'dindigul', 'Natham', 'Nilakottai', 'Oddanchatram', 'Palani', 'Vedasandur'],
    'Kanchipuram': ['Acharapakkam', 'Alandur', 'Chengalpattu', 'kancheepuram', 'Maduranthakam','Sriperumbadar','Tambaram','Tiruporur','Uthiramerur'],
    'Kanyakumari': ['Colachel', 'kanniyakumari', 'killiyur','Nagercoil','Padmanabhapuram','Thiruvattar','Vilavancode'],
    'Karur': ['Aruvakurichi', 'Karur', 'Krishnarayapuram','Kulithalai'],
    'Krishnagiri': ['Bargur', 'Hosur', 'Kavaeripattinam','Krishnagiri','Thalli'],
    'Madurai': ['madurai', 'Melur', 'Samayanallur','Sedapatti','Sholavandan','Thirumangalam','Thiruparankundram','Usilampatti'],
    'Nagapattinam': ['Kuttalam', 'Mayiladuthurai', 'nagapattinam','Poompuhar','Sirkali','Vedaranyam'],
    'Namakkal': ['Kapilamalai', 'Namakkal', 'Rasipuram','Sankari','Sendamangalam','Tiruchengode'],
    'Nilgiris': ['Coonoor', 'Gudalur', 'Ooatacamund'],
    'Perambalur': ['Alathur', 'Jayankondam', 'Kunnam','Perambalur','Varahur','Veppanthattai'],
    'Pudukkottai': ['Alangudi', 'Aranthangi', 'Kolathur','Pudukkottai','Thirumayam'],
    'Ramanathapuram': ['Kadaladi', 'Mudukulathur', 'Paramakudi','ramanathapuram','Thiruvadanai'],
    'Salem': ['Athur', 'Edapadi', 'Mettur','Omalur','Panamarathupatty','salem','Talavasal','Taramangalam','Veerapandi','Yercaud'],
    'Sivaganga': ['Ilayangudi', 'Karaikudi', 'Manamadurai','sivaganga','Tiruppathur'],
    'Thanjavur': ['Kumbakonam', 'Orathanad', 'Papanasam','Pattukottai','thanjavur','Thiruvidaimaruthur','Thiruvonam','Tiruvaiyaru'],
    'Theni': ['Bodinayakkanur','Andipatti','Cumbam', 'Periyakulam', 'theni'],
    'Thoothukudi(Tuticorin)': ['Kayalpatnam', 'Koilpatti', 'Ottapidaram','Sattangulam','Srivaikuntam','tiruchendur','Tuticorin','Vilathikulam'],
    'Thiruchirappalli': ['Lalkudi', 'Marungapuri', 'Musiri','Srirangam','Tiruverumbur','Thottiam','Thiruchirapalli','Uppiliapuram'],
    'Tirunelveli': ['Alangulam', 'Ambasamudram', 'Cheranmahadevi','Kedayanallur','Nanguneri','Palayamkottai','Puliyangudi','Radhapuram','Sankaranayanarkoil','Tenkasi','tirunelveli','Vasudevanallur'],
    'Tiruppur': ['Dharapuram', 'Kangeyam', 'Nallur','Palladam','tirupur','Udumalaipettai','Velampalayam','Vellakoil'],
    'Tiruvallur': ['Gummidipoondi', 'Pakkipet', 'Ponneri','Poonamalle','Thiruttani','Thiruvallur','Thiruvottiyur','Villivakkam'],
    'Tiruvannamalai': ['Arni', 'Chengam', 'Cheyyar','Kalasapakkam','Peranamallur','Polur','Thandarambattu','tiruvannamalai','Vandavasi'],
    'Thiruvarur': ['Mannargudi', 'Nannilam', 'Tiruthuraipoondi','tiruvarur','Valangiman'],
    'Vellore': ['Vellore'],
    'Viluppuram': ['Chinnsalem', 'Gingee', 'Kandamangalam','Melmalayanur','Mugaiyur','Rishivandiam','Sankarapuram','Thirunavalur','Tindivanam','Tirukoilur','Ulundurpet','Vanur','villupuram'],
    'Virudhunagar': ['Aruppukottai', 'Rajapalayam', 'Sattur','Sivakasi','Srivillithur','virudhunagar'],
    'Chengalpattu': ['Mahabalipuram', 'Tambaram', 'chengalpattu'],
    'Ranipet': ['Arakkonam', 'Kalavai', 'Kilarasampet','Narasingapuram','Panapakam','ranipet','Sholinghur','Walajapet'],
    'Tenkasi': ['Achampudur', 'Alangulam', 'Alwarkurichi','Aygudi','Courtallam','Ilanji','Keezhapavur','Mekagaram','Panpoli','Pudur','Puliyankudi','Rayagiri','Sambavarvadakarai','Sankarankovil','Sengottai',
                'Sivagiri','Sundarapandiapuram','Surandai','tenkasi','Thirukadam','Vasudevanallur','Veerakeralampudur'],
    'Kallakurichi': ['Chinnaselam', 'Kallakurichi', 'Manalurpet','Mattigaikurichi','Moongilthuraipattu','Rishivandiyam','Somandargudi','Thiagadurgam','Tirukoilur','Ulundurpettai','Vadakkanandai'],
    'Mayiladuthurai': ['Kornad', 'Kuthalam', 'Manalmedu','mayiladuthurai','Palaiyur','Poombuhar','Puhar','Sembanarkoil','Sirkazhi','Tharangambadi','Thirumanancheri','Thiruvaduthurai','Thiruvilandur','Vaitheeswarankoil'],
    'Tirupattur': ['Ambur', 'tirupattur', 'vaniyambadi','Jolarpet'],
}